"use client";

import {
  LayoutDashboard,
  Bell,
  Calendar,
  Users,
  Shield,
  BarChart3,
  Leaf,
  Sprout,
  Tractor,
  Sun,
  Droplet,
  Heart,
  Code,
  Terminal,
  BookOpen,
  Play,
  GraduationCap,
  Package,
  Camera,
  MapPin,
  Flower2,
  Search,
  Smartphone,
  Star,
  type LucideIcon,
} from "lucide-react";

import type { LucideIconKey } from "@/lib/projects";

export const LUCIDE_MAP: Record<LucideIconKey, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  bell: Bell,
  calendar: Calendar,
  users: Users,
  shield: Shield,
  "bar-chart": BarChart3,
  leaf: Leaf,
  sprout: Sprout,
  tractor: Tractor,
  sun: Sun,
  droplet: Droplet,
  heart: Heart,
  code: Code,
  terminal: Terminal,
  "book-open": BookOpen,
  play: Play,
  "graduation-cap": GraduationCap,
  package: Package,
  camera: Camera,
  "map-pin": MapPin,
  flower: Flower2,
  search: Search,
  smartphone: Smartphone,
  star: Star,
};
